version: "3"
services:
  prometheus_server:
    image: prom/prometheus:v2.17.0
    volumes:
    - type: volume
      source: pro_vol
      target: /prometheus
    - /opt/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
    privileged: true

  grafana_server:
    image: grafana/grafana:10.0.0
    volumes:
    - type: volume
      source: grafana_vol
      target: /etc/grafana
    - type: volume
      source: grafana_vol
      target: /var/lib/grafana
    ports:
    - 3000:3000
    privileged: true

  vmware_exporter:
    image: pryorda/vmware_exporter:v0.11.1
    ports:
    - 9272:9272
    environment:
      VSPHERE_HOST: <HOST_IP>
      VSPHERE_IGNORE_SSL: True
      VSPHERE_USER: <USER>
      VSPHERE_PASSWORD: "<PASSWORD>"

volumes:
  prometheus_data:
  grafana_configuration:
  grafana_data:
